load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pugixml",
    include_prefix = "pugixml",
    hdrs = glob(["*.hpp"]),
    srcs = glob(["*.cpp"]),
)